# Based on https://github.com/taiki-e/parse-changelog/blob/777a82184bcbe0ed975e63a491f5fbf80b29cb1b/.github/workflows/ci.yml

name: Rust CI

permissions:
  contents: read

on:
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows other workflows to call this one
  workflow_call:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings
  RUSTDOCFLAGS: --deny warnings
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustc, cargo, rustfmt, rust-std, clippy, rust-src, rust-analysis

      - name: Check format
        run: cargo fmt --all --check
      - name: Clippy
        run: cargo clippy --workspace --all-features --all-targets
      - name: Build
        run: cargo build --verbose
      - name: Build --no-default-features
        run: cargo build --verbose --no-default-features
      - name: Build --all-features
        run: cargo build --verbose --all-features --all-targets
      - name: Run tests
        run: cargo test --verbose --lib --examples
      - name: Run tests --all-features
        run: cargo test --verbose --all-features --lib --examples
